
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpjnuasoahkwcirpssxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwam51YXNvYWhrd2NpcnBzc3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODMwNDksImV4cCI6MjA2MTM1OTA0OX0.suD62tmRnTxoaMG0xRAdOAHEBNW2LkaM7OmwS5xfATY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce' // Changed from 'implicit' to 'pkce' for better security
    }
  }
);
